// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY DATASHEET. DO NOT CHANGE IT.
// </auto-generated>

namespace SoundEventLink
{
    public enum ExposedType
    {
        Bool = 204392422,
        Float = 613690240,
        String = -983920443,
        Object = 2051284657,
    }
}
#if UNITY_EDITOR
namespace SoundEventLink.GeneratedEditor
{
    public class ExposedTypeTypeGetter : global::DataSheet.Editor.IVariableTypeGetter
    {
        public global::DataSheet.Editor.VariableType GetVariableType() => new global::DataSheet.Editor.VariableType(typeof(global::SoundEventLink.ExposedType));
    }
}
#endif
