// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY DATASHEET. DO NOT CHANGE IT.
// </auto-generated>

namespace SoundEventLink
{
    public enum SoundEventLinkType
    {
        なし = 1424737353,
        参照 = -1633690383,
        オリジナル = 1972026933,
    }
}
#if UNITY_EDITOR
namespace SoundEventLink.GeneratedEditor
{
    public class SoundEventLinkTypeTypeGetter : global::DataSheet.Editor.IVariableTypeGetter
    {
        public global::DataSheet.Editor.VariableType GetVariableType() => new global::DataSheet.Editor.VariableType(typeof(global::SoundEventLink.SoundEventLinkType));
    }
}
#endif
